#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinxcontrib-newsfeed
Version  : 0.1.4
Release  : 25
URL      : http://pypi.debian.net/sphinxcontrib-newsfeed/sphinxcontrib-newsfeed-0.1.4.tar.gz
Source0  : http://pypi.debian.net/sphinxcontrib-newsfeed/sphinxcontrib-newsfeed-0.1.4.tar.gz
Summary  : News Feed extension for Sphinx
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-newsfeed-license = %{version}-%{release}
Requires: sphinxcontrib-newsfeed-python = %{version}-%{release}
Requires: sphinxcontrib-newsfeed-python3 = %{version}-%{release}
Requires: Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-python

%description
****************************************************************
``sphinxcontrib-newsfeed`` -- News Feed extension for Sphinx
****************************************************************

%package license
Summary: license components for the sphinxcontrib-newsfeed package.
Group: Default

%description license
license components for the sphinxcontrib-newsfeed package.


%package python
Summary: python components for the sphinxcontrib-newsfeed package.
Group: Default
Requires: sphinxcontrib-newsfeed-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-newsfeed package.


%package python3
Summary: python3 components for the sphinxcontrib-newsfeed package.
Group: Default
Requires: python3-core

%description python3
python3 components for the sphinxcontrib-newsfeed package.


%prep
%setup -q -n sphinxcontrib-newsfeed-0.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551037951
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-newsfeed
cp LICENSE %{buildroot}/usr/share/package-licenses/sphinxcontrib-newsfeed/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-newsfeed/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
